jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        i686:
          MINGW_UPPER: MINGW32
          MINGW_LOWER: mingw32
          MINGW_ARCH: i686
        x86_64:
          MINGW_UPPER: MINGW64
          MINGW_LOWER: mingw64
          MINGW_ARCH: x86_64
    steps:
      - script: git clone https://github.com/lazka/msys2-ci-base.git %CD:~0,2%\msys64
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
        displayName: Update MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm --needed -S git base-devel mingw-w64-$(MINGW_ARCH)-toolchain
        displayName: Install Toolchain
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc "bash ci-build.sh"
        displayName: CI-Build
        env:
          MSYSTEM: $(MINGW_UPPER)
          CHERE_INVOKING: yes
          MINGW_INSTALLS: $(MINGW_LOWER)
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_ACCOUNT: Alexpux
          PACMAN_REPOSITORY_NAME: ci.mingw
      - task: PublishBuildArtifacts@1
        displayName: Publish packages
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/artifacts
          artifactName: mingw-$(MINGW_ARCH)
